import { firebaseConfig, OWNER_EMAIL } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, updateProfile, signOut } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, collection, addDoc, query, orderBy, onSnapshot, serverTimestamp, limit, writeBatch, runTransaction } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const fb=initializeApp(firebaseConfig), auth=getAuth(fb), db=getFirestore(fb);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let mode='login', me=null, profile=null, sales=[], purchases=[], historicalStore=[], expenses=[], users=[], publicStats={stockDiamonds:0}, migrationState='';
const money=n=>`${new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0))} SAR`;
const num=n=>new Intl.NumberFormat('en-US').format(Number(n||0));
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function setMode(m){mode=m;$('#tabLogin').classList.toggle('active',m==='login');$('#tabSignup').classList.toggle('active',m==='signup');$$('.signupOnly').forEach(x=>x.classList.toggle('hidden',m!=='signup'));$('#authBtn').textContent=m==='login'?'دخول':'إنشاء الحساب';$('#password').autocomplete=m==='login'?'current-password':'new-password'}
$('#tabLogin').onclick=()=>setMode('login');$('#tabSignup').onclick=()=>setMode('signup');
$('#authForm').onsubmit=async e=>{e.preventDefault();const msg=$('#authMsg');msg.textContent='جاري التحقق…';try{let cred;if(mode==='login')cred=await signInWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value);else{cred=await createUserWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value);await updateProfile(cred.user,{displayName:$('#name').value.trim()||'مشرف'});}msg.textContent='تم.'}catch(err){msg.textContent=human(err)}};
function human(e){const c=e?.code||'',m={"auth/invalid-credential":"البريد أو كلمة المرور غير صحيحة.","auth/email-already-in-use":"البريد مسجل مسبقًا.","auth/weak-password":"كلمة المرور ضعيفة.","auth/too-many-requests":"محاولات كثيرة، انتظر قليلًا."};return m[c]||e.message||'حدث خطأ'}
$('#logout').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{if(!user){me=profile=null;$('#gate').classList.remove('hidden');$('#app').classList.add('hidden');return}me=user;await ensureProfile();if(profile.status==='disabled' && profile.role!=='owner'){await signOut(auth);alert('الحساب موقوف حتى يفعّله المالك.');return}$('#gate').classList.add('hidden');$('#app').classList.remove('hidden');applyRole();if(profile.role==='owner') await ensureHistoricalMigration();subscribe();show('dashboard')});
async function ensureProfile(){const ref=doc(db,'users',me.uid),snap=await getDoc(ref);const owner=me.email?.toLowerCase()===OWNER_EMAIL.toLowerCase();if(!snap.exists()){profile={uid:me.uid,email:me.email,name:me.displayName||me.email,role:owner?'owner':'supervisor',status:owner?'active':'pending',createdAt:serverTimestamp()};await setDoc(ref,profile)}else{profile=snap.data();if(owner&&(profile.role!=='owner'||profile.status!=='active')){await updateDoc(ref,{role:'owner',status:'active'});profile={...profile,role:'owner',status:'active'}}}}

async function ensureHistoricalMigration(){
  const migrationId='v21_full_history_2026_07_14';
  const migRef=doc(db,'migrations',migrationId);
  const existing=await getDoc(migRef);
  if(existing.exists()){migrationState='تم نقل البيانات التاريخية';return}
  migrationState='جاري نقل البيانات التاريخية…';
  try{
    const res=await fetch('./historical-data.json',{cache:'no-store'});
    if(!res.ok) throw new Error('تعذر تحميل ملف البيانات التاريخية');
    const payload=await res.json();
    const ops=[];
    const safeId=(prefix,id,i)=>String(id||`${prefix}_${i}`).replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,180);
    (payload.store||[]).forEach((row,i)=>ops.push([doc(db,'storeEntries',safeId('store',row.id,i)),{...row,legacySource:'v21',migratedAt:serverTimestamp()}]));
    (payload.broadcast||[]).forEach((row,i)=>ops.push([doc(db,'broadcasterCommissions',safeId('bc',row.id,i)),{...row,legacySource:'v21',migratedAt:serverTimestamp()}]));
    (payload.aliases||[]).forEach((row,i)=>ops.push([doc(db,'broadcasterAliases',safeId('alias',row.id,i)),{...row,legacySource:'v21',migratedAt:serverTimestamp()}]));
    (payload.imports||[]).forEach((row,i)=>ops.push([doc(db,'importBatches',safeId('imp',row.id,i)),{...row,legacySource:'v21',migratedAt:serverTimestamp()}]));
    (payload.lockedMonths||[]).forEach((row,i)=>ops.push([doc(db,'lockedMonths',safeId('lock',row.id||row,i)),typeof row==='object'?{...row}:{month:row}]));
    const settings=payload.settings||{};
    const opening=Number(settings.openingDiamonds||0);
    const purchased=(payload.store||[]).reduce((a,r)=>a+Number(r.diamondsPurchased||0),0);
    const sold=(payload.store||[]).reduce((a,r)=>a+Number(r.diamondsSold||0),0);
    const stock=Math.max(0,opening+purchased-sold);
    ops.push([doc(db,'appSettings','main'),{...settings,sourceVersion:payload.version||'v21',sourceExportedAt:payload.exportedAt||'',updatedAt:serverTimestamp()}]);
    ops.push([doc(db,'publicStats','current'),{stockDiamonds:stock,historicalStoreCount:(payload.store||[]).length,historicalBroadcastCount:(payload.broadcast||[]).length,lastUpdatedAt:serverTimestamp()}]);
    for(let i=0;i<ops.length;i+=430){const batch=writeBatch(db);ops.slice(i,i+430).forEach(([ref,data])=>batch.set(ref,data,{merge:true}));await batch.commit()}
    await setDoc(migRef,{status:'completed',source:'dot-almasiah-backup-2026-07-15.json',exportedAt:payload.exportedAt||'',storeCount:(payload.store||[]).length,broadcastCount:(payload.broadcast||[]).length,completedAt:serverTimestamp(),completedBy:me.uid});
    migrationState=`تم نقل ${(payload.store||[]).length} سجل متجر و${(payload.broadcast||[]).length} سجل مذيعين`;
  }catch(err){console.error(err);migrationState='تعذر النقل التلقائي: '+(err.message||err)}
}

function applyRole(){const owner=profile.role==='owner';$$('.ownerOnly').forEach(x=>x.classList.toggle('hidden',!owner));$('#rolePill').textContent=owner?'المالك · '+me.email:'مشرف مبيعات · '+(profile.name||me.email)}
function subscribe(){onSnapshot(doc(db,'publicStats','current'),s=>{if(s.exists())publicStats=s.data();if(current==='dashboard')dashboard()},console.error);const saleQ=query(collection(db,'sales'),orderBy('createdAt','desc'),limit(500));onSnapshot(saleQ,s=>{sales=s.docs.map(d=>({id:d.id,...d.data(),sourceType:'cloud'}));if(current==='dashboard'||current==='sales')show(current)},console.error);if(profile.role==='owner'){onSnapshot(query(collection(db,'storeEntries'),orderBy('date','desc'),limit(1000)),s=>{historicalStore=s.docs.map(d=>({id:d.id,...d.data(),sourceType:'historical'}));if(current==='dashboard'||current==='sales'||current==='purchases')show(current)},console.error);onSnapshot(query(collection(db,'users'),orderBy('createdAt','desc')),s=>{users=s.docs.map(d=>({id:d.id,...d.data()}));if(current==='users')show('users')});onSnapshot(query(collection(db,'purchases'),orderBy('createdAt','desc'),limit(500)),s=>{purchases=s.docs.map(d=>({id:d.id,...d.data(),sourceType:'cloud'}));if(current==='purchases')show('purchases')});onSnapshot(query(collection(db,'expenses'),orderBy('createdAt','desc'),limit(500)),s=>{expenses=s.docs.map(d=>({id:d.id,...d.data()}));if(current==='expenses')show('expenses')})}}
let current='dashboard';const titles={dashboard:['لوحة التحكم','متابعة العمليات أولًا بأول'],newSale:['تسجيل مبيعة','إضافة عملية جديدة إلى قائمة الاعتماد'],sales:['سجل المبيعات','جميع المبيعات وحالات الاعتماد'],users:['المستخدمون والصلاحيات','تفعيل وإيقاف حسابات المشرفين'],purchases:['المشتريات والمخزون','إضافة مشتريات الألماس ومتابعة الرصيد'],expenses:['المصاريف','تسجيل المصروفات ومتابعتها'],legacy:['قسم المذيعين والتقارير v21','فتح لوحة DOT ALMASIAH v21 الأصلية']};
$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
function show(v){current=v;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#viewTitle').textContent=titles[v][0];$('#viewSub').textContent=titles[v][1];if(v==='dashboard')dashboard();if(v==='newSale')newSale();if(v==='sales')salesView();if(v==='users')usersView();if(v==='purchases')purchasesView();if(v==='expenses')expensesView();if(v==='legacy')legacy()}
function mine(arr=sales){return profile.role==='owner'?arr:arr.filter(x=>x.createdBy===me.uid)}

function historicalSales(){return historicalStore.filter(x=>Number(x.diamondsSold||0)>0||Number(x.salesIncl||0)>0).map((x,i)=>({id:`hist_${x.id}`,orderNumber:`H-${String(i+1).padStart(3,'0')}`,saleDate:x.date,diamonds:Number(x.diamondsSold||0),amount:Number(x.salesIncl||0),payment:x.paymentSource==='store'?'المتجر':'—',customer:'—',createdByName:'سجل تاريخي',createdByEmail:'',status:'approved',sourceType:'historical',notes:x.notes||''}))}
function historicalPurchases(){return historicalStore.filter(x=>Number(x.diamondsPurchased||0)>0||Number(x.purchasesIncl||0)>0).map(x=>({id:`histp_${x.id}`,purchaseDate:x.date,diamonds:Number(x.diamondsPurchased||0),amount:Number(x.purchasesIncl||0),supplier:'سجل تاريخي',createdByEmail:'—',sourceType:'historical',notes:x.notes||''}))}
function allSales(){const cloud=mine(sales);return profile.role==='owner'?[...cloud,...historicalSales()].sort((a,b)=>String(b.saleDate||'').localeCompare(String(a.saleDate||''))):cloud}
function allPurchases(){return [...purchases,...historicalPurchases()].sort((a,b)=>String(b.purchaseDate||'').localeCompare(String(a.purchaseDate||'')))}
function shortOrder(x){if(x.sourceType==='historical')return `#H${String(x.orderNumber||'').replace(/\D/g,'').slice(-3)||'—'}`;const digits=String(x.orderNumber||'').replace(/\D/g,'');return digits?`#${digits.slice(-6)}`:'#—'}
function sourceBadge(x){return `<span class="source ${x.sourceType==='historical'?'historical':'cloud'}">${x.sourceType==='historical'?'تاريخي':'سحابي'}</span>`}
function detailsButton(x){return `<button class="order-mini" data-detail="${esc(x.id)}" title="عرض التفاصيل">${esc(shortOrder(x))}</button>`}
function bindDetails(a){$$('[data-detail]').forEach(b=>b.onclick=()=>{const x=a.find(r=>r.id===b.dataset.detail);if(!x)return;const full=x.orderNumber||x.id;alert(`رقم الطلب: ${full}\nالتاريخ: ${x.saleDate||'—'}\nالألماس: ${num(x.diamonds)}\nالمبلغ: ${money(x.amount)}\nطريقة الدفع: ${x.payment||'—'}\nالعميل: ${x.customer||'—'}\nالملاحظات: ${x.notes||'—'}`)})}

function dashboard(){const a=allSales(),today=new Date().toISOString().slice(0,10),tod=a.filter(x=>x.saleDate===today),pending=sales.filter(x=>x.status==='pending');$('#content').innerHTML=`${migrationState?`<div class="notice">${esc(migrationState)}</div>`:''}<div class="grid4"><div class="card metric"><span>مبيعات اليوم</span><b>${money(tod.reduce((s,x)=>s+Number(x.amount||0),0))}</b></div><div class="card metric"><span>الألماس اليوم</span><b class="gold">${num(tod.reduce((s,x)=>s+Number(x.diamonds||0),0))}</b></div><div class="card metric"><span>المخزون الحالي</span><b class="gold">${num(publicStats.stockDiamonds||0)}</b></div><div class="card metric"><span>بانتظار الاعتماد</span><b>${num(pending.length)}</b></div></div><div class="section"><h3>آخر العمليات</h3>${table(a.slice(0,10))}</div>`;bindDetails(a.slice(0,10));bindApprovals()}
function newSale(){$('#content').innerHTML=`<div class="notice">تُحفظ العملية كمسودة «بانتظار الاعتماد». لا تدخل في الإجماليات المعتمدة حتى يعتمدها المالك.</div><div class="card"><form id="saleForm" class="formgrid"><div class="field"><label>تاريخ المبيعة</label><input id="saleDate" type="date" required value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>كمية الألماس</label><input id="diamonds" type="number" min="1" required></div><div class="field"><label>مبلغ البيع بالريال</label><input id="amount" type="number" min="0" step="0.01" required></div><div class="field"><label>طريقة الدفع</label><select id="payment" required><option value="المتجر">المتجر</option><option value="تحويل بنكي">تحويل بنكي</option></select></div><div class="field"><label>اسم العميل / المذيع</label><input id="customer"></div><div class="field"><label>رقم الطلب المرجعي (اختياري)</label><input id="reference"></div><div class="field wide"><label>ملاحظات</label><textarea id="notes" rows="3"></textarea></div><div class="wide"><button class="primary" id="saveSale">حفظ العملية</button><span id="saleMsg" class="msg" style="margin-right:12px"></span></div></form></div>`;$('#saleForm').onsubmit=async e=>{e.preventDefault();const btn=$('#saveSale'),msg=$('#saleMsg');btn.disabled=true;msg.textContent='جاري الحفظ…';try{const autoOrder=`DM-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Date.now().toString().slice(-6)}`;await addDoc(collection(db,'sales'),{orderNumber:autoOrder,saleDate:$('#saleDate').value,diamonds:Number($('#diamonds').value),amount:Number($('#amount').value),payment:$('#payment').value,customer:$('#customer').value.trim(),reference:$('#reference').value.trim(),notes:$('#notes').value.trim(),status:'pending',createdBy:me.uid,createdByName:profile.name||me.email,createdByEmail:me.email,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});msg.textContent='تم تسجيل العملية وإرسالها للاعتماد.';e.target.reset();$('#saleDate').value=new Date().toISOString().slice(0,10)}catch(err){msg.textContent=human(err)}finally{btn.disabled=false}}}
function table(a){if(!a.length)return '<div class="empty card">لا توجد عمليات حتى الآن.</div>';const rows=a.map(x=>`<tr><td>${detailsButton(x)}</td><td>${esc(x.saleDate)}</td><td>${num(x.diamonds)}</td><td>${money(x.amount)}</td><td>${esc(x.customer||'—')}</td><td>${sourceBadge(x)}</td><td><span class="status ${x.status}">${x.status==='pending'?'بانتظار الاعتماد':x.status==='approved'?'معتمد':'مرفوض'}</span></td><td>${profile.role==='owner'&&x.status==='pending'&&x.sourceType!=='historical'?`<div class="actions"><button class="secondary" data-approve="${x.id}">اعتماد</button><button class="secondary danger" data-reject="${x.id}">رفض</button></div>`:'—'}</td></tr>`).join('');const cards=a.map(x=>`<article class="sale-card"><div class="sale-top"><div><span class="sale-label">كمية الألماس</span><strong class="sale-diamonds">${num(x.diamonds)}</strong></div>${sourceBadge(x)}</div><div class="sale-amount">${money(x.amount)}</div><div class="sale-meta"><span>${esc(x.customer||'بدون اسم')}</span><span>${esc(x.saleDate||'—')}</span></div><div class="sale-bottom"><span class="status ${x.status}">${x.status==='pending'?'بانتظار الاعتماد':x.status==='approved'?'معتمد':'مرفوض'}</span>${detailsButton(x)}</div>${profile.role==='owner'&&x.status==='pending'&&x.sourceType!=='historical'?`<div class="sale-actions"><button class="secondary" data-approve="${x.id}">اعتماد</button><button class="secondary danger" data-reject="${x.id}">رفض</button></div>`:''}</article>`).join('');return `<div class="desktop-table tablewrap"><table><thead><tr><th>رقم العملية</th><th>التاريخ</th><th>الألماس</th><th>المبلغ</th><th>العميل</th><th>المصدر</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>${rows}</tbody></table></div><div class="mobile-cards">${cards}</div>`}
function bindApprovals(){$$('[data-approve]').forEach(b=>b.onclick=()=>decision(b.dataset.approve,'approved'));$$('[data-reject]').forEach(b=>b.onclick=()=>decision(b.dataset.reject,'rejected'))}
async function decision(id,status){
  const saleRef=doc(db,'sales',id), statsRef=doc(db,'publicStats','current');
  await runTransaction(db,async tx=>{const saleSnap=await tx.get(saleRef);if(!saleSnap.exists())throw new Error('العملية غير موجودة');const sale=saleSnap.data();if(sale.status!=='pending')return;let patch={status,approvedBy:me.uid,approvedByEmail:me.email,approvedAt:serverTimestamp(),updatedAt:serverTimestamp()};if(status==='approved'){const st=await tx.get(statsRef);const current=Number(st.data()?.stockDiamonds||0), qty=Number(sale.diamonds||0);if(current<qty)throw new Error('المخزون غير كافٍ لاعتماد العملية');tx.set(statsRef,{stockDiamonds:current-qty,lastUpdatedAt:serverTimestamp()},{merge:true});patch.stockDeducted=qty;}tx.update(saleRef,patch)}).catch(e=>alert(e.message||e))
}
function salesView(){const a=allSales();$('#content').innerHTML=`<div class="grid4"><div class="card metric"><span>عدد العمليات</span><b>${num(a.length)}</b></div><div class="card metric"><span>المعتمد</span><b>${num(a.filter(x=>x.status==='approved').length)}</b></div><div class="card metric"><span>المعلّق</span><b>${num(sales.filter(x=>x.status==='pending').length)}</b></div><div class="card metric"><span>إجمالي القيمة</span><b>${money(a.reduce((s,x)=>s+Number(x.amount||0),0))}</b></div></div><div class="section">${table(a)}</div>`;bindApprovals();bindDetails(a)}

function purchasesView(){if(profile.role!=='owner')return show('dashboard');const all=allPurchases(),totalQty=all.reduce((a,x)=>a+Number(x.diamonds||0),0),totalCost=all.reduce((a,x)=>a+Number(x.amount||0),0);$('#content').innerHTML=`<div class="grid4"><div class="card metric"><span>المخزون الحالي</span><b class="gold">${num(publicStats.stockDiamonds||0)}</b></div><div class="card metric"><span>إجمالي الألماس المشترى</span><b>${num(totalQty)}</b></div><div class="card metric"><span>إجمالي قيمة المشتريات</span><b>${money(totalCost)}</b></div><div class="card metric"><span>عدد عمليات الشراء</span><b>${num(all.length)}</b></div></div><div class="section card"><h3>إضافة مشتريات</h3><form id="purchaseForm" class="formgrid"><div class="field"><label>التاريخ</label><input id="purchaseDate" type="date" required value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>كمية الألماس</label><input id="purchaseDiamonds" type="number" min="1" required></div><div class="field"><label>قيمة الشراء بالريال</label><input id="purchaseAmount" type="number" min="0" step="0.01" required></div><div class="field"><label>المورد / الجهة</label><input id="supplier"></div><div class="field wide"><label>ملاحظات</label><textarea id="purchaseNotes" rows="2"></textarea></div><div class="wide"><button class="primary">حفظ وإضافة للمخزون</button><span id="purchaseMsg" class="msg"></span></div></form></div><div class="section"><h3>سجل المشتريات</h3>${all.length?`<div class="tablewrap"><table><thead><tr><th>التاريخ</th><th>الألماس</th><th>القيمة</th><th>المورد</th><th>المصدر</th></tr></thead><tbody>${all.map(x=>`<tr><td>${esc(x.purchaseDate)}</td><td>${num(x.diamonds)}</td><td>${money(x.amount)}</td><td>${esc(x.supplier||'—')}</td><td>${sourceBadge(x)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty card">لا توجد مشتريات حتى الآن.</div>'}</div>`;$('#purchaseForm').onsubmit=async e=>{e.preventDefault();const qty=Number($('#purchaseDiamonds').value),amount=Number($('#purchaseAmount').value),statsRef=doc(db,'publicStats','current'),pRef=doc(collection(db,'purchases'));try{await runTransaction(db,async tx=>{const st=await tx.get(statsRef),current=Number(st.data()?.stockDiamonds||0);tx.set(pRef,{purchaseDate:$('#purchaseDate').value,diamonds:qty,amount,supplier:$('#supplier').value.trim(),notes:$('#purchaseNotes').value.trim(),createdBy:me.uid,createdByEmail:me.email,createdAt:serverTimestamp()});tx.set(statsRef,{stockDiamonds:current+qty,lastUpdatedAt:serverTimestamp()},{merge:true})});$('#purchaseMsg').textContent='تمت الإضافة وتحديث المخزون.';e.target.reset();$('#purchaseDate').value=new Date().toISOString().slice(0,10)}catch(err){$('#purchaseMsg').textContent=err.message||err}}}
function expensesView(){if(profile.role!=='owner')return show('dashboard');const total=expenses.reduce((a,x)=>a+Number(x.amount||0),0);$('#content').innerHTML=`<div class="grid4"><div class="card metric"><span>إجمالي المصاريف</span><b>${money(total)}</b></div><div class="card metric"><span>عدد المصاريف</span><b>${num(expenses.length)}</b></div><div class="card metric"><span>مصاريف هذا الشهر</span><b>${money(expenses.filter(x=>(x.expenseDate||'').slice(0,7)===new Date().toISOString().slice(0,7)).reduce((a,x)=>a+Number(x.amount||0),0))}</b></div><div class="card metric"><span>الخصوصية</span><b style="font-size:16px">للمالك فقط</b></div></div><div class="section card"><h3>تسجيل مصروف</h3><form id="expenseForm" class="formgrid"><div class="field"><label>التاريخ</label><input id="expenseDate" type="date" required value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>المبلغ</label><input id="expenseAmount" type="number" min="0" step="0.01" required></div><div class="field"><label>التصنيف</label><select id="expenseCategory"><option>رواتب</option><option>تسويق وإعلانات</option><option>عمولات تحويل</option><option>اشتراكات وبرامج</option><option>رسوم بنكية</option><option>ضريبة</option><option>مصاريف تشغيل</option><option>أخرى</option></select></div><div class="field"><label>الجهة / المستفيد</label><input id="expensePayee"></div><div class="field"><label>طريقة الدفع</label><select id="expensePayment"><option>تحويل بنكي</option><option>المتجر</option><option>أخرى</option></select></div><div class="field"><label>المرجع</label><input id="expenseReference"></div><div class="field wide"><label>ملاحظات</label><textarea id="expenseNotes" rows="2"></textarea></div><div class="wide"><button class="primary">حفظ المصروف</button><span id="expenseMsg" class="msg"></span></div></form></div><div class="section"><h3>سجل المصاريف</h3>${expenses.length?`<div class="tablewrap"><table><thead><tr><th>التاريخ</th><th>التصنيف</th><th>المبلغ</th><th>المستفيد</th><th>الدفع</th></tr></thead><tbody>${expenses.map(x=>`<tr><td>${esc(x.expenseDate)}</td><td>${esc(x.category)}</td><td>${money(x.amount)}</td><td>${esc(x.payee||'—')}</td><td>${esc(x.payment||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty card">لا توجد مصاريف سحابية بعد.</div>'}</div>`;$('#expenseForm').onsubmit=async e=>{e.preventDefault();try{await addDoc(collection(db,'expenses'),{expenseDate:$('#expenseDate').value,amount:Number($('#expenseAmount').value),category:$('#expenseCategory').value,payee:$('#expensePayee').value.trim(),payment:$('#expensePayment').value,reference:$('#expenseReference').value.trim(),notes:$('#expenseNotes').value.trim(),createdBy:me.uid,createdByEmail:me.email,createdAt:serverTimestamp()});$('#expenseMsg').textContent='تم حفظ المصروف.';e.target.reset();$('#expenseDate').value=new Date().toISOString().slice(0,10)}catch(err){$('#expenseMsg').textContent=err.message||err}}}

function usersView(){if(profile.role!=='owner')return show('dashboard');$('#content').innerHTML=`<div class="notice">حسابات المشرفين الجديدة تبدأ بحالة «بانتظار التفعيل». فعّل فقط الحسابات المعروفة لك.</div><div class="tablewrap"><table><thead><tr><th>الاسم</th><th>البريد</th><th>الدور</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.name||'—')}</td><td>${esc(u.email)}</td><td>${u.role==='owner'?'مالك':'مشرف'}</td><td>${esc(u.status)}</td><td>${u.role==='owner'?'—':`<button class="secondary" data-user="${u.id}" data-status="${u.status==='active'?'disabled':'active'}">${u.status==='active'?'إيقاف':'تفعيل'}</button>`}</td></tr>`).join('')}</tbody></table></div>`;$$('[data-user]').forEach(b=>b.onclick=()=>updateDoc(doc(db,'users',b.dataset.user),{status:b.dataset.status,updatedAt:serverTimestamp()}))}
function legacy(){$('#content').innerHTML=`<div class="notice">هذا هو قسم المذيعين والرواتب والتقارير الأصلي من النسخة v21، محمّل معه تاريخك حتى 13 يوليو 2026. الوحدات السحابية الجديدة للمبيعات والمشتريات والمصاريف تعمل في الواجهة الرئيسية.</div><div class="card" style="text-align:center;padding:35px"><h3>لوحة التقارير الأصلية</h3><p style="color:var(--muted)">تفتح في تبويب مستقل.</p><a class="primary" style="display:inline-block;text-decoration:none" href="./legacy-dashboard.html" target="_blank">فتح اللوحة الأصلية</a></div>`}
